# Generated by Django 4.1.5 on 2023-01-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Наименование')),
                ('discount', models.PositiveSmallIntegerField(default=0, verbose_name='Процентаная скидка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('archived', models.BooleanField(default=False, verbose_name='Статус')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
