from django.urls import path

from .views import (
    ShopPage,
    ProductList,
    OrderList,
    CreateProduct,
    OrderCreate,
    UpdateProduct,
    UpdateOrder,
    DetailProduct,
    ArchivedProduct,
    OrderDetail,
    OrderDelete,
    OrderListByUser,
    Contact,
    OrdersExport,
    ShowProductsPage,
    CartAdd,
    CartDetail,
    CartDelete,
    CartUpdate,
    CatalogProducts,
    ProductOffer,

)

app_name = "shopapp"
urlpatterns = [
    path("", ShopPage.as_view(), name="shop_page"),
    path("contact/", Contact.as_view(), name="contact"),
    path("products/", ProductList.as_view(), name="products_list"),
    path("products/create/", CreateProduct.as_view(), name="create_product"),
    path("products/<int:pk>/detail/", DetailProduct.as_view(), name="product_detail"),
    path("products/<int:pk>/update/", UpdateProduct.as_view(), name="update_product"),
    path("products/<int:pk>/archived/", ArchivedProduct.as_view(), name="product_archived"),
    path("catalog/<str:eng_name>/", CatalogProducts.as_view(), name="catalog_products"),
    path("products_by_category/<str:slug>/", ShowProductsPage.as_view(), name="products_by_category"),
    # path("catalog/<int:pk>/", ShowElectronicPage.as_view(), name="appliances"),
    # path("catalog/<int:pk>/", ShowElectronicPage.as_view(), name="beauty_and_health"),
    # path("catalog/<int:pk>/", ShowElectronicPage.as_view(), name="cloth"),
    # path("catalog/<int:pk>/", ShowElectronicPage.as_view(), name="shoes"),
    # path("catalog/<int:pk>/", ShowElectronicPage.as_view(), name="construction_and_repair"),
    # path("catalog/<int:pk>/", ShowElectronicPage.as_view(), name="childens_goods"),
    # path("filter/", ShowCategoryPage.as_view(), name="filters"),
    # path("catalog/<int:pk>/", ShowElectronicPage.as_view(), name="electronics"),
    path("orders/", OrderList.as_view(), name="orders_list"),
    path("orders_export/", OrdersExport.as_view(), name="orders_export"),
    path("orders/create/", OrderCreate.as_view(), name="create_order"),
    path("orders/<int:pk>/user/", OrderListByUser.as_view(), name="orders_user"),
    path("orders/<int:pk>/detail/", OrderDetail.as_view(), name="order_detail"),
    path("orders/<int:pk>/update/", UpdateOrder.as_view(), name="update_order"),
    path("orders/<int:pk>/delete/", OrderDelete.as_view(), name="order_delete"),
    path('cart/all/', CartDetail.as_view(), name='cart_detail'),
    path('cart/add/<int:product_id>/', CartAdd.as_view(), name='cart_add'),
    path('cart/update/<int:product_id>/', CartUpdate.as_view(), name='cart_update'),
    path('cart/remove/<int:product_id>/', CartDelete.as_view(), name='cart_remove'),
    path('offers/', ProductOffer.as_view(), name='offers'),
]
