# Generated by Django 4.1.5 on 2023-01-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='archived',
            field=models.BooleanField(choices=[(1, False), (2, True)], default=False, verbose_name='Статус'),
        ),
    ]
