# Generated by Django 4.1.6 on 2023-02-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/default_image.jpg', upload_to='images/', verbose_name='Изображение продукта'),
        ),
    ]
