# Generated by Django 4.1.6 on 2023-02-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='image/default_image.jpg', upload_to='images', verbose_name='Изображение продукта'),
        ),
    ]
