# Generated by Django 4.1.5 on 2023-01-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('uploadedFile', models.FileField(blank=True, null=True, unique=True, upload_to='', verbose_name='Файл')),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Файлы',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
